const Actions = {
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  REMOVE_CREATE_PRODUCT: 'REMOVE_CREATE_PRODUCT',
  CURRENT_PRODUCT: 'CURRENT_PRODUCT',
  TOAST: 'TOAST',
  CLEAR_TOAST: 'CLEAR_TOAST',

  PRODUCT_NAME: 'PRODUCT_NAME',
  PRODUCT_DESCRIPTION: 'PRODUCT_DESCRIPTION',
  PRODUCT_NUMBER: 'PRODUCT_NUMBER',
  PRODUCT_PRICE: 'PRODUCT_PRICE',
  PRODUCT_IMAGE: 'PRODUCT_IMAGE',
  PRODUCT_IMAGE_REMOVE: 'PRODUCT_IMAGE_REMOVE',
  PRODUCT_CLEAR_FIELDS: 'PRODUCT_CLEAR_FIELDS',
  PRODUCT_SET: 'PRODUCT_SET',

  DIALOG_OPEN: 'DIALOG_OPEN',
  DIALOG_CLOSE: 'DIALOG_CLOSE',
};

export default Actions;
